name: Tests and analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: _test_storm
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: CRLF
      run: |
        git config --global core.autocrlf true

    - uses: actions/checkout@v2

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo, pdo_mysql, json, tokenizer, mbstring

    - name: Check PHP Version
      run: php -v
    - name: Check Composer Version
      run: composer -V
    - name: Check PHP Extensions
      run: php -m

    - name: Check PHP info
      run: php -i

    - name: Check PHP locate
      run: cat /etc/php/8.2/cli/conf.d/20-pdo_mysql.ini

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Run commit check
      run: composer check-commit

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: download
      run: curl https://raw.githubusercontent.com/liquiddesign/storm/main/tests/_sql/_test_storm.sql --output _test_storm.sql

    - name: mysql
      run: mysql -h 127.0.0.1 -u root _test_storm < _test_storm.sql

    - name: Run phpstan
      run: composer phpstan
    
    - name: Run phpcs
      run: composer phpcs

    - name: Run phpcheck7
      run: composer phpcheck7

    - name: Run phpcheck8
      run: composer phpcheck8

    - name: Run tester
      run: composer tester

    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,author
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: failure()
